data:
  image: busybox
  volumes:
    - /app:/app

db:
  image: postgres
  volumes_from:
    - data
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: arista
    POSTGRES_PASSWORD: arista1234
    PGDATA: /app/data/pgdata

server:
  image: google/dart:1.11.3
  volumes_from:
    - data
  links:
   - db
  ports:
    - "80:9090"
  command: bash -c "cd /app/arista-server && pub get && dart bin/server.dart"